# This override file is used for local development.
# It enables hot-reloading for both the frontend and backend services.

services:
  backend:
    # Mount the backend source code into the container.
    # Any changes you make locally will be reflected inside the container.
    volumes:
      - ./LGS_Stock_Backend:/app

  frontend:
    # Override the build context to use the development Dockerfile.
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development-stage
    ports:
      - "5173:5173" # Expose Vite's port instead of Nginx's
    volumes:
      - ./frontend:/app
      # This is an anonymous volume to prevent node_modules on the host
      # from overwriting the container's node_modules.
      - /app/node_modules
