# This override file is used for local development.
# It is merged with the base docker-compose.yml to enable hot-reloading
# and add development-specific services.

x-common-backend-env: &common-backend-env
  LOG_LEVEL: ${LOG_LEVEL:-DEBUG} # Default to DEBUG for local development
  FLASK_CONFIG: development

services:
  backend:
    # Override the production command to run the dev server with hot-reloading.
    command: [ "python", "run.py" ]
    volumes:
      # Mount the source code into the container.
      - ./LGS_Stock_Backend:/app
    ports:
      # Expose the backend port for direct access/debugging.
      - "5000:5000"
    environment:
      <<: *common-backend-env

  frontend:
    # Override the build context to use the development Dockerfile.
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      # Anonymous volume to prevent host node_modules from overwriting the container's.
      - /app/node_modules
    ports:
      # Override the production port mapping.
      # Expose the Vite dev server's port (5173) to the host.
      - "5173:5173"

  worker:
    volumes:
      - ./LGS_Stock_Backend:/app
    environment:
      <<: *common-backend-env

  # --- Development-only services ---

  dozzle:
    image: amir20/dozzle:latest
    container_name: lgs-stock-checker-dozzle-1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"
    networks:
      - stock-net

  rq-dashboard:
    image: eoranged/rq-dashboard:latest
    container_name: lgs-stock-checker-rq-dashboard-1
    restart: unless-stopped
    ports:
      - "9181:9181"
    environment:
      RQ_DASHBOARD_REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    depends_on:
      - redis
    networks:
      - stock-net
