# This file is for development-specific overrides.
# It is automatically used by `docker compose up` in a local environment.
# It should NOT be checked into version control if it contains secrets.

services:
  backend:
    volumes:
      - ./LGS_Stock_Backend:/app/LGS_Stock_Backend
  frontend:
    # Override for development to use Vite's dev server
    build:
      context: ./LGS_Stock_Frontend
      dockerfile: Dockerfile
      target: development-stage
    ports:
      - "5173:5173" # Expose Vite's port instead of Nginx's
    volumes:
      # Mount source code for hot-reloading.
      # The node_modules directory is a separate, anonymous volume
      # to prevent the host's node_modules from overwriting the container's.
      - ./LGS_Stock_Frontend:/app
      - /app/node_modules
